site_name: TOTVS ADDONS
site_url: https://fsw-mi-totvsoeste.gitlab.io/documentacao-eletronica/
repo_url: https://gitlab.com/fsw-mi-totvsoeste/documentacao-eletronica

theme:
  name: material
  language: pt
  logo: assets/totvs_icon_write.png
  favicon: assets/totvs_icon.png
  palette:
    - scheme: default
      primary: custom
      accent: orange

  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.action.edit
    - content.tabs.link

nav:
  - Inicio: index.md
  - Addons:
    - Projeto FS99_001:
      - Alçadas - Regras: addon-alcadas-regras.md
      - Alçadas com Workflow - Pedido de Venda: addon-alcadas-pedido-venda.md
      - Alçadas - Pedidos de Compras: addon-alcadas-pedido-compras.md
      - Alçadas - Contas a Pagar: addon-alcadas-contas-pagar.md   
    - Projeto FS99_003:
      - CNAB A Receber: addon-cnab-a-receber.md
      - CNAB A Pagar: addon-cnab-a-pagar.md
      - CNAB Folha: addon-cnab-folha.md
      - CNAB Extrato Bancario: addon-cnab-extrato-bancario.md 
    - Projeto FS99_004:
      - Addon Importação de XML: addon-xml-terceiro.md
    - Projeto FS99_006:
      - Addon Comissões e Faturamento: addon-comissoes-faturamento.md
    - Projeto FS99_007:  
      - Addon de Leite: addon-leite.md
    - Projeto FS99_009:  
      - Addon Processo de Workflow de Alçadas Cadastrais: addon-alcadas-workflow-cadastrais.md
  - Suporte: suporte.md         

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - toc:      
      permalink: false      
      toc_depth: 3

extra_css:
  - stylesheets/extra.css